# ==============================================================================
# run_r_methods_imputation_power.R
#
# Companion R-method runner for the non-null imputation power benchmark.
# Reads InputData feather files generated by imputation_power_benchmark.py
# and runs COPF and PeCorA on each (strategy, run) pair to produce
# identification TPR curves (and COPF grouping TPR).
#
# Input files expected:
#   Revisions/outputs/simulation/imputation_benchmark/power_inputs/
#       power_<strategy>_run_<kk>_InputData.feather
#
# Usage:
#   PF_STRATEGIES=downshift,minprob,zero_fill,global_mean,knn,hybrid_downshift_knn,no_imputation \
#   PF_OVERWRITE=0 \
#   Rscript Revisions/logic/r/simulation/fdr_calibration/run_r_methods_imputation_power.R
# ==============================================================================

overall_start <- Sys.time()
options(warn = -1)

# ── Early-exit cache guard ─────────────────────────────────────────────────────
# Skip everything (including renv + library loading) when outputs already exist.
.overwrite_env <- tolower(Sys.getenv("PF_OVERWRITE", unset = "0"))
.outputs_exist <- all(file.exists(file.path(
  Sys.getenv("PF_OUTDIR",
    file.path(getwd(), "Revisions", "outputs", "simulation", "imputation_benchmark")),
  "tables",
  c("r_methods_identification_tpr_curves.csv",
    "r_methods_identification_tpr_summary.csv")
)))
if (!(.overwrite_env %in% c("1", "true", "yes", "y", "on")) && .outputs_exist) {
  cat("[R power driver] All outputs exist and PF_OVERWRITE=0 — skipping.\n")
  quit(save = "no", status = 0)
}

# ── Environment ────────────────────────────────────────────────────────────────
script_dir <- tryCatch(
  dirname(sys.frame(1)$ofile),
  error = function(e) getwd()
)

if (grepl("fdr_calibration$", script_dir)) {
  project_root <- normalizePath(file.path(script_dir, "..", "..", "..", "..", ".."))
} else {
  project_root <- getwd()
}
# Print relative paths only
rel_path <- function(p) {
  sub(paste0("^", gsub("([.|()\\^{}+$*?]|\\[|\\])", "\\\\\\1", project_root), "/?"), "", p)
}
cat("Project root: .\n")

renv_activate <- file.path(project_root, "renv", "activate.R")
if (file.exists(renv_activate)) source(renv_activate)

setwd(project_root)

suppressMessages(library(arrow,      warn.conflicts = FALSE))
suppressMessages(library(data.table, warn.conflicts = FALSE))
suppressMessages(library(CCprofiler, warn.conflicts = FALSE))
suppressMessages(library(PeCorA,     warn.conflicts = FALSE))
suppressMessages(library(stringr,    warn.conflicts = FALSE))

# ── Parameters ─────────────────────────────────────────────────────────────────
overwrite <- tolower(Sys.getenv("PF_OVERWRITE", unset = "0")) %in% c("1", "true", "yes", "y", "on")

strategy_raw <- Sys.getenv("PF_STRATEGIES", unset = "downshift,minprob,zero_fill,global_mean,knn,hybrid_downshift_knn,no_imputation")
strategies <- unlist(strsplit(strategy_raw, ","))
strategies <- trimws(strategies)
strategies <- strategies[nchar(strategies) > 0]

allowed <- c("downshift", "minprob", "zero_fill", "global_mean", "knn", "hybrid_downshift_knn", "no_imputation")
invalid <- setdiff(strategies, allowed)
if (length(invalid) > 0) {
  stop("Unsupported strategy in PF_STRATEGIES: ", paste(invalid, collapse = ", "))
}

score_cutoff <- 0.0
adj_pval_cutoff <- 1.1

output_root <- file.path(project_root, "Revisions", "outputs", "simulation", "imputation_benchmark")
input_dir <- file.path(output_root, "power_inputs")
r_cache_dir <- file.path(output_root, "r_methods_power")
table_dir <- file.path(output_root, "tables")
dir.create(r_cache_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(table_dir, recursive = TRUE, showWarnings = FALSE)

alpha_log <- exp(seq(log(1e-15), log(0.01), length.out = 25))
alpha_mid <- seq(0.01, 0.10, by = 0.005)
alpha_coarse <- seq(0.10, 0.90, by = 0.10)
alpha_grid <- sort(unique(round(c(alpha_log, alpha_mid, alpha_coarse), 15)))

# ── Helpers ────────────────────────────────────────────────────────────────────
fmt_time <- function(secs) {
  if (secs < 60) return(sprintf("%.1f sec", secs))
  if (secs < 3600) return(sprintf("%.1f min", secs / 60))
  sprintf("%.2f hr", secs / 3600)
}

extract_run_id <- function(path) {
  m <- regexpr("run_[0-9]+", basename(path))
  if (m[1] == -1) return(NA_integer_)
  token <- regmatches(basename(path), m)
  as.integer(sub("run_", "", token))
}

collect_inputs <- function(strategy) {
  pattern <- sprintf("^power_%s_run_[0-9]+_InputData\\.feather$", strategy)
  files <- list.files(input_dir, pattern = pattern, full.names = TRUE)
  if (length(files) == 0) return(data.table())
  dt <- data.table(path = files)
  dt[, run := vapply(path, extract_run_id, integer(1))]
  dt <- dt[!is.na(run)]
  setorder(dt, run)
  dt
}

# ── Collectors ─────────────────────────────────────────────────────────────────
copf_tpr_rows <- list()
pec_tpr_rows  <- list()
time_rows     <- list()

cat("================================================================================\n")
cat("Imputation POWER benchmark R methods (COPF + PeCorA)\n")
cat("Strategies:", paste(strategies, collapse = ", "), "\n")
cat("Input dir:", rel_path(input_dir), "\n")
cat("Output dir:", rel_path(output_root), "\n")
cat("overwrite:", overwrite, "\n")
cat("================================================================================\n\n")

for (strategy in strategies) {
  input_index <- collect_inputs(strategy)
  if (nrow(input_index) == 0) {
    cat("[", strategy, "] no input files found, skipping\n", sep = "")
    next
  }

  cat("[", strategy, "] runs: ", nrow(input_index), "\n", sep = "")

  for (i in seq_len(nrow(input_index))) {
    run <- input_index$run[i]
    input_file <- input_index$path[i]

    run_start <- Sys.time()

    copf_cache <- file.path(r_cache_dir, sprintf("copf_%s_run%02d.feather", strategy, run))
    pec_cache  <- file.path(r_cache_dir, sprintf("pecora_%s_run%02d.feather", strategy, run))

    # ==========================================================================
    # COPF
    # ==========================================================================
    if (overwrite || !file.exists(copf_cache)) {
      t0 <- Sys.time()
      input_data <- as.data.table(arrow::read_feather(input_file))
      input_data[, peptide_id := paste(Protein, Peptide, sep = "-")]
      setnames(input_data, c("Protein", "Intensity", "Sample"), c("protein_id", "intensity", "filename"))

      input_annot <- unique(input_data[, .(filename, Condition)])
      setorderv(input_annot, c("Condition", "filename"))
      input_annot[, fraction_number := .I]
      input_annot <- input_annot[, .(filename, fraction_number)]

      trace_annot <- unique(input_data[, .(peptide_id, pertProtein, pertPeptide, pertPFG)])
      trace_annot <- trace_annot[!duplicated(peptide_id)]

      traces <- CCprofiler::importPCPdata(input_data = input_data, fraction_annotation = input_annot)
      traces <- CCprofiler::annotateTraces(
        traces,
        trace_annot,
        traces_id_column = "id",
        trace_annotation_id_column = "peptide_id",
        uniprot_mass_format = FALSE
      )

      zerovar <- apply(CCprofiler::getIntensityMatrix(traces), 1, var) > 0
      traces <- subset(traces, trace_subset_ids = names(zerovar[zerovar]))
      traces <- CCprofiler::filterSinglePeptideHits(traces)
      traces <- CCprofiler::calculateGeneCorrMatrices(traces)
      traces <- CCprofiler::clusterPeptides(
        traces,
        method = "average",
        plot = FALSE,
        PDF = FALSE,
        name = sprintf("COPF_power_%s_run%02d", strategy, run)
      )
      traces <- CCprofiler::cutClustersInNreal(
        traces,
        clusterN = 2,
        min_peptides_per_cluster = 2
      )
      traces <- CCprofiler::calculateProteoformScore(traces)
      traces_final <- CCprofiler::annotateTracesWithProteoforms(
        traces,
        score_cutoff = score_cutoff,
        adj_pval_cutoff = adj_pval_cutoff
      )

      ta <- as.data.frame(traces_final$trace_annotation)
      ta$strategy <- strategy
      ta$run <- run
      arrow::write_feather(ta, copf_cache)

      time_rows[[length(time_rows) + 1]] <- list(
        strategy = strategy, run = run, method = "COPF",
        stage = "recomputed",
        seconds = as.numeric(difftime(Sys.time(), t0, units = "secs"))
      )
    } else {
      time_rows[[length(time_rows) + 1]] <- list(
        strategy = strategy, run = run, method = "COPF",
        stage = "cache_hit",
        seconds = as.numeric(difftime(Sys.time(), run_start, units = "secs"))
      )
    }

    copf_df <- as.data.table(arrow::read_feather(copf_cache))
    # TPR: fraction of pertPeptide==TRUE peptides with significant p-val
    pert_copf <- copf_df[pertPeptide == TRUE | pertPeptide == "True"]
    n_pert_copf <- nrow(pert_copf)
    for (a in alpha_grid) {
      if (n_pert_copf > 0) {
        n_det <- sum(pert_copf$proteoform_score_pval < a, na.rm = TRUE)
        tpr_val <- n_det / n_pert_copf
      } else {
        n_det <- 0L
        tpr_val <- NA_real_
      }
      copf_tpr_rows[[length(copf_tpr_rows) + 1]] <- list(
        method = "COPF", strategy = strategy, run = run,
        alpha = a, tpr = tpr_val, n_total = n_pert_copf, n_detected = n_det
      )
    }

    # ==========================================================================
    # PeCorA
    # ==========================================================================
    if (overwrite || !file.exists(pec_cache)) {
      t0 <- Sys.time()
      orig_data <- arrow::read_feather(input_file)
      input_data <- as.data.table(copy(orig_data))
      setnames(input_data, c("Intensity", "Sample"), c("Normalized.Area", "filename"))
      input_data[, Peptide.Modified.Sequence := paste(Protein, Peptide, sep = "-")]

      ann <- unique(input_data[, .(filename, Condition)])
      setorderv(ann, c("Condition", "filename"))
      ann[, BioReplicate := as.integer(stringr::str_extract(filename, "(?<=-)([1-9]|10)$"))]
      input_data <- merge(input_data, ann, by = c("filename", "Condition"))
      input_data <- input_data[, .(
        Protein, Peptide, Peptide.Modified.Sequence,
        Condition, BioReplicate, Normalized.Area
      )]
      pecora_df <- setDF(input_data)

      scaled_peptides <- PeCorA::PeCorA_preprocessing(
        pecora_df,
        area_column_name = 6,
        threshold_to_filter = min(pecora_df$Normalized.Area),
        control_name = "control"
      )
      disagree <- PeCorA::PeCorA(scaled_peptides)

      pecora_res <- as.data.table(disagree)
      pecora_res[, peptide_id := gsub("_all", "", peptide)]
      pecora_res[, c("Protein", "Peptide") := tstrsplit(peptide_id, "-", fixed = TRUE)]

      orig_dt <- as.data.table(orig_data)
      pert_info <- unique(orig_dt[, .(Protein, Peptide, pertProtein, pertPeptide, pertPFG)])

      final_pec <- merge(
        pecora_res[, .(Protein, Peptide, pvalue, adj_pval)],
        pert_info,
        by = c("Protein", "Peptide")
      )
      final_pec$strategy <- strategy
      final_pec$run <- run
      arrow::write_feather(as.data.frame(final_pec), pec_cache)

      time_rows[[length(time_rows) + 1]] <- list(
        strategy = strategy, run = run, method = "PeCorA",
        stage = "recomputed",
        seconds = as.numeric(difftime(Sys.time(), t0, units = "secs"))
      )
    } else {
      time_rows[[length(time_rows) + 1]] <- list(
        strategy = strategy, run = run, method = "PeCorA",
        stage = "cache_hit",
        seconds = as.numeric(difftime(Sys.time(), run_start, units = "secs"))
      )
    }

    pec_df <- as.data.table(arrow::read_feather(pec_cache))
    pert_pec <- pec_df[pertPeptide == TRUE | pertPeptide == "True"]
    n_pert_pec <- nrow(pert_pec)
    for (a in alpha_grid) {
      if (n_pert_pec > 0) {
        n_det <- sum(pert_pec$adj_pval < a, na.rm = TRUE)
        tpr_val <- n_det / n_pert_pec
      } else {
        n_det <- 0L
        tpr_val <- NA_real_
      }
      pec_tpr_rows[[length(pec_tpr_rows) + 1]] <- list(
        method = "PeCorA", strategy = strategy, run = run,
        alpha = a, tpr = tpr_val, n_total = n_pert_pec, n_detected = n_det
      )
    }

    run_elapsed <- as.numeric(difftime(Sys.time(), run_start, units = "secs"))
    cat(sprintf("  [%s] run %02d done in %s\n", strategy, run, fmt_time(run_elapsed)))
  }
}

# ── Save outputs ───────────────────────────────────────────────────────────────
tpr_df <- rbindlist(c(copf_tpr_rows, pec_tpr_rows), fill = TRUE)

if (nrow(tpr_df) > 0) {
  fwrite(tpr_df, file.path(table_dir, "r_methods_identification_tpr_curves.csv"))
  tpr_summary <- tpr_df[, .(
    tpr_mean = mean(tpr, na.rm = TRUE),
    tpr_sd = sd(tpr, na.rm = TRUE)
  ), by = .(method, strategy, alpha)]
  tpr_summary[is.na(tpr_sd), tpr_sd := 0.0]
  fwrite(tpr_summary, file.path(table_dir, "r_methods_identification_tpr_summary.csv"))
}

if (length(time_rows) > 0) {
  timing_df <- rbindlist(time_rows, fill = TRUE)
  fwrite(timing_df, file.path(table_dir, "runtime_timing_r_methods_power.csv"))
}

cat("\nDone. Elapsed:", fmt_time(as.numeric(difftime(Sys.time(), overall_start, units = "secs"))), "\n")
cat("Tables written to:", rel_path(table_dir), "\n")
